Category.find_or_create_by(name: 'World News')
Category.find_or_create_by(name: 'Science')
Category.find_or_create_by(name: 'Business')
Category.find_or_create_by(name: 'Tech')
Category.find_or_create_by(name: 'Entertainment')
Category.find_or_create_by(name: 'Culture')
Category.find_or_create_by(name: 'Sports')
