Article.find_or_create_by(title: "Pablo Escobar: Colombia sterilises drug lord's hippos",
                          lede: "Scientists are concered about the impact of the rogue non-native herd near Escobar's former ranch.",
                          body: "A group of hippos - an unwanted legacy following the death of notorious Colombian drug lord Pablo Escobar - are being sterilised. Escobar, who was shot dead by police in 1993, illegally imported exotic animals, including a male and a female hippo - dubbed the 'cocaine hippos'. Since then, a growing population has been taking over the countryside near his former ranch, Hacienda Nápoles.  The Colombian government has so far sterilised 24 of more than 80 animals. They have been treated with a chemical that will make them infertile. Colombian environmentalists say the hippos, believed to be the biggest herd outside Africa, are an invasive species and have pushed away the native fauna. Many have campaigned for the animals to be culled or sterilised. Back in 1993, when authorities seized Hacienda Nápoles - Escobar's luxury estate situated about 250km (155 miles) north-west of the capital Bogotá - most of the animals found there were distributed to zoos across the country. But not the hippos. 'It was logistically difficult to move them around, so the authorities just left them there, probably thinking the animals would die,' Colombian biologist Nataly Castelblanco told the BBC earlier this year. However, with no natural predators in South America, the hippos multiplied. Hippos at Hacienda Nápoles, once the private zoo of drug kingpin Pablo Escobar, in Colombia, 12 September 2020 According to experts, they started spreading through one of the country's main waterways - the River Magdalena. Scientists studying the hippos' environmental impact say the animals could affect the local ecosystem in a number of ways: from displacing native species already under threat of extinction, like the manatee, to altering the chemical compositions of waterways, which could endanger fisheries - though other studies suggest they might help the environment too. Escobar, one of the most notorious South American criminals of all time, was the founder of the infamous Medellín drugs cartel in the 1980s, responsible for kidnappings, bombings and indiscriminate assassinations. At one point he was thought to be one of the world's richest men.",
                          category_id: 1,
                          category_name: 'World News',
                          published: true)

Article.find_or_create_by(title: 'Net zero announcement: UK sets out plans to cut greenhouse gas emissions',
                          lede: 'The government reveals its long-awaited strategy days beofre global leaders meet for COP26 in Glasgow.',
                          body: "Another big push towards electric vehicles is being made in the UK government's latest strategy to make the great shift to a virtually zero-carbon economy. Ministers are investing £620m in grants for electric vehicles and street charging points. Car makers will be mandated to sell a proportion of clean vehicles each year. An extra £350m is promised to help the automotive supply chain move to electric. The new plan set out by the government is supposed to dramatically reduce greenhouse gas emissions to reach a target of net zero by 2050. The announcement comes 12 days before global leaders meet in Glasgow to negotiate how to curb climate change. Achieving net zero means the UK will no longer be adding to the total amount of greenhouse gases in the atmosphere. Without action on climate change, the world faces a hotter planet, rising sea levels and extreme weather that threaten many forms of life. The UK has already made progress in cutting emissions compared to the levels released in 1990. In 2019, the country released 40% less than in 1990. On Tuesday the government also announced a strategy to address emissions from the UK's 30 million buildings. Homeowners will be able to apply for grants of up to £5,000 to install low-carbon heat pumps to replace gas boilers. The Labour party's Ed Miliband responded to the strategy, saying the 'plans falls short on delivery' adding 'we've waited months for a heat and buildings strategy, it's a massive let-down'. Prof Lord Nicholas Stern, Chair of LSE's Grantham Research Institute on Climate Change and the Environment, said the plan will require 'strong investment and innovation' and would generate a 'new and attractive form of growth. But he warned that low-income households will need support. And Prof Dan Lunt, Professor of Climate Science at University of Bristol, called the strategy's approach to flying weak and unambitious.",
                          category_id: 2,
                          category_name: 'Science & Enviroment',
                          published: true)

Article.find_or_create_by(title: 'Net zero announcement: UK sets out plans to cut greenhouse gas emissions',
                          lede: "Forget the pyramids, the canals of Venice or the Eiffel Tower – the Swedish government plans to make Sweden the world's top tourism destination by 2030.",
                          body: "Forget the pyramids, the canals of Venice or the Eiffel Tower – the Swedish government has presented a plan to make Sweden the world's most attractive tourism destination by 2030 – but it's not yet clear how. In a press conference on Monday, Sweden’s Minister for Business, Industry and Innovation Ibrahim Baylan outlined the new strategy, which aims to make Sweden “the world’s most sustainable and attractive tourism destination built on innovation” by 2030. Baylan referred to Sweden as a country which “is usually ranked as one of the world’s most innovative countries”, which he argued can “create value for the tourism industry”. According to Baylan, the strategy builds on “sustainability’s three dimensions – it has to be environmentally, socially and economically sustainable”. The strategy will also “tie into the UN’s Sustainable Development Goals for 2030”, he said. Topics covered by the new tourism strategy include the climate impact of tourism, equality and inclusion in the tourism industry and the importance of preserving shared resources such as national parks and sustainable nature tourism such as fishing and hunting. The press release highlights the importance of natural tourism, explaining that the pandemic has led to people visiting natural and cultural environments “to a greater extent than before”, increasing wear and tear to natural areas. Tourism is an important industry for Sweden, providing employment in both urban and rural areas, as well as generating wealth – before the coronavirus pandemic, the tourism industry represented on average 2.7 percent of Sweden’s GDP per year. The tourism industry also employs a high amount of people from foreign backgrounds – making up over a third (34 percent) of all employees in the industry. During the pandemic, overnight stays declined in almost every Swedish municipality, with the biggest declines seen in Sweden’s larger cities and border municipalitites. The government’s plans also include a focus on jobs and skill development, so that workers have the right qualifications for the industry – this reflects issues currently faced by the restaurant and hotel industry in finding skilled workers in the wake of the pandemic. There are currently no details as to how the government will achieve this strategy, or indeed how it will measure success. But Sweden is aiming high if it wants to be the world’s most attractive tourist destination by 2030. In 2019, it was ranked the 54th top tourist destination in the world by the UN World Tourism Organisation.",
                          category_id: 6,
                          category_name: 'Culture & Health',
                          published: true)
