User.create(name: 'Roger Harrabin', email: 'roger@nip.com', role: 2, password: 'password')
User.create(name: 'Emily Anthes', email: 'emily@nip.com', role: 2, password: 'password')
User.create(name: 'Becky Waterton', email: 'becky@nip.com', role: 2, password: 'password')
User.create(name: 'Pascale Hughes', email: 'pascale@nip.com', role: 2, password: 'password')
User.create(name: 'Fraser Hughes', email: 'fraser@nip.com', role: 3, password: "password")
User.create(name: 'Matthew Henry', email: 'matthew@nip.com', role: 2, password: "password")
